version: "3.9"

services:
  api:
    container_name: jit_api
    build:
      context: ./
      dockerfile: Docker/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./Docker/php/php.ini:/usr/local/etc/php/app.conf/php.ini
    depends_on:
      - server
      - redis
      - database
    networks:
      - jit_network

  server:
    container_name: jit_server
    image: nginx:latest
    restart: unless-stopped
    tty: true
    user: root
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jit_network

  redis:
    container_name: jit_redis
    image: redis:latest
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - jit_network

  database:
    container_name: jit_mysql
    image: mysql
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql/
      - ./Docker/mysql/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Docker/mysql/mysql.conf:/etc/mysql/mysql.conf
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - jit_network

networks:
  jit_network:
    name: jit_network
    driver: bridge

volumes:
    database:
        driver: local
    redis:
        driver: local
